name: dysaeatsflutter
description: "App móvil para pedidos y mensajería"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_messaging: ^15.2.4  # Actualizado según la sugerencia
  
  # Autenticación
  google_sign_in: ^6.3.0
  
  # Estado
  provider: ^6.1.2
  
  # UI y utilidades
  flutter_dotenv: ^5.1.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  http: ^1.3.0
  
  # Mapas y ubicación
  google_maps_flutter: ^2.11.0
  location: ^5.0.3
  geolocator: ^13.0.3
  geocoding: ^2.2.2
  flutter_polyline_points: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
